### ISSUE TITLE
V3.0.3 Cpanel results in:  Call to undefined method Joomla\CMS\Log\Logger::addLogger()

### ISSUE THREAD

**Issue by seanaustingmailcom** [MLWebTechnologies/PrayerCenter#14]
3.0.3

**Comment by seanaustingmailcom** [comment]
Cpanel barely works if I set PHP to v5.4 - when I update to PHP 7.0 it throws the error.  Good to see updates happening though!  :)

**Comment by Piotr2ma** [comment]
Not a solution, but a workaround - in the file administrator\components\com_prayer\views\prayercenter\tmpl\default.php commenting out lines 420-429 makes a cpanel working.  
Hope this helps :-)

**Comment by MLWebTechnologies** [comment]
seanaustingmailcom, my test site is PHP 5.6.33 and Joomla 3.8.6, which seems to work error free.  The addLogger() function is native to Joomla.  Not sure if it is supported on PHP 7.  I will be doing more research on it.  Thanks.

**Comment by MLWebTechnologies** [comment]
Piotr, thank you for the workaround suggestion.  Can you tell me what PHP and Joomla versions your site is running?   I may have to create my own logging function...

**Comment by Piotr2ma** [comment]
blockquote {padding-left: 1ex; margin: 0px 0px 0px 0.8ex; border-left: #cccccc 1px solid;} p {margin: 0px;padding: 0px;} 
I have production site with joomla 3.8.6 (latest with php 5.6.23 ) and test site with php 5.6 na 7.1
For me it seems that version of php is only symptom but not a source. Probably the source lays in changes in Joomla engine
 
Best wishes
 
Piotr
 
Dnia Piątek, 13 Kwietnia 2018 15:26 MLWebTechnologies <notifications@github.com> napisał(a)

Piotr, thank you for the workaround suggestion. Can you tell me what PHP and Joomla versions your site is running? I may have to create my own logging function...
—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
 
// <![CDATA[
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MLWebTechnologies/PrayerCenter","title":"MLWebTechnologies/PrayerCenter","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in 
GitHub","url":"https://github.com/MLWebTechnologies/PrayerCenter"}},"updates":{"snippets":[{"icon":"PERSON","message":"@MLWebTechnologies in #14: Piotr, thank you for the workaround suggestion.  Can you tell me what PHP and Joomla versions your site is running?   I may have to create my own logging function..."}],"action":{"name":"View Issue","url":"https://github.com/MLWebTechnologies/PrayerCenter/issues/14#issuecomment-381134507"}}}
// ]]>

**Comment by Piotr2ma** [comment]
I have made ashort digging in Joomla docs and I hope I have found solution. As I mentioned in previous post problem exists in file  administrator\components\com_prayer\views\prayercenter\tmpl\default.php 
There are number of calls of fuctions of JLogLogger class. Yo have to change the name to JLog and control panel stops to complain about undefined method.  Lines 420-429 should look as follows:
						JLog::addLogger(
							array(
								'text_file' => 'com_prayercenter/pcerrorlog.php',
								'text_entry_format' => '{DATE} {TIME} {MESSAGE}'
							),
							JLog::ALL,
							array('com_prayercenter')
						);
						JLog::add();
						$logstring = JFile::read( $logfiledir.'/com_prayercenter/pcerrorlog.php' );
					}

Hope this helps.
Piotr
