### ISSUE TITLE
Error when install installing 

### ISSUE THREAD

**Issue by GODpleasers** [MLWebTechnologies/PrayerCenter#17]
Error when install installing 

Warning
JInstaller: :Install: File does not exist /home/godpleasers/public_html/tmp/install_5ae09b7bbfd76/admin/help
Component Install: Failed to copy administrator files.
Error
Error installing component

COM_PRAYERCENTER_XML_DESCRIPTION

![prayercentererror](https://user-images.githubusercontent.com/13956002/39255470-792cae4a-4861-11e8-81d1-69f1aa9f7622.JPG)

___________________________________
Joomla! 3.8.7
PHP Version 7.0.29 
    Server type: MySQL
    Server version: 5.6.38 - MySQL Community Server (GPL)

**Comment by MLWebTechnologies** [comment]
Odd that this error is showing up...didn't in testing.   I'm almost done with 3.0.4.  Should be releasing this weekend.  I will make sure this issue is taking care of as well.  Thanks!

**Comment by GODpleasers** [comment]
Thanks look forward to it could it be our php version?

**Comment by MLWebTechnologies** [comment]
I'm thinking it may be more to do with the newer Joomla version(s).  They might be less tolerant of errors...and they should be...:)

**Comment by GODpleasers** [comment]
-Anyhow thanks for you hard work in updating this we love it great component.

**Comment by Piotr2ma** [comment]
Hi, the source of the problem is in prayercenter.xml manifest file. In section `<administration>` there is a definition of folder **help** which does not exist in instalation package. Removing such line makes package prayercenter installing propperly.
Part of above mentioned section regarding files & admin folders should look as follows:
![obraz](https://user-images.githubusercontent.com/38132165/39291739-463610fc-4934-11e8-8a6a-3101a6e4edd7.png)
Piotr
